### ISSUE TITLE
How can i get your induced trees?

### ISSUE THREAD

**Issue by lezhang7** [jonathanherzig/span-based-sp#2]
I want to investigate the induced trees, but how to get it and download it in a file?

**Comment by nixonjin** [comment]
自动回复：这里是金能征的邮箱，您的信件已被收入。This is Jin Nengzheng. Your letter have been received and will be disposed as soon as possible.

**Comment by jonathanherzig** [comment]
Hi,
The predicted span-trees can be found at:
https://github.com/jonathanherzig/span-based-sp/blob/7c7f87b8ef9d3061652cd25758869e78b57179a4/span_based/utils/cky.py#L487

The can printed using: `print(span_tree.show(data_property="to_string"))`

**Comment by nixonjin** [comment]
自动回复：这里是金能征的邮箱，您的信件已被收入。This is Jin Nengzheng. Your letter have been received and will be disposed as soon as possible.

**Comment by lezhang7** [comment]
Hello sir,

When I try to reproduce your results on teplate_span_f1,  I follow the
default settings, and my command is "python span_based/run_span.py -d
geo_template_f1 -w -l" but it turns out that:
[image: 0e4cc79eb5487ae83f0f631d1259082.png]
I can't figure out why the results are so far below the reported one, and
my work is based on yours, so could you tell me a little bit about it?



[image: Mailtrack]
<https://mailtrack.io?utm_source=gmail&utm_medium=signature&utm_campaign=signaturevirality5&>
Sender
notified by
Mailtrack
<https://mailtrack.io?utm_source=gmail&utm_medium=signature&utm_campaign=signaturevirality5&>
22/01/20
上午10:14:29

Jonathan Herzig ***@***.***> 于2022年1月2日周日 00:45写道：

**Comment by nixonjin** [comment]
自动回复：这里是金能征的邮箱，您的信件已被收入。This is Jin Nengzheng. Your letter have been received and will be disposed as soon as possible.

**Comment by jonathanherzig** [comment]
Hi, 
Sorry, but I can't see the attached image

Jonathan

**Comment by lezhang7** [comment]
Hi,
The image is the result I run your code python span_based/run_span.py -d
geo_template_f1 -w -l, and the epoch is 250, best test_den_acc=0.64,
test_seq_acc=0.588, best_epoch=230, this is far from the results reported
in the paper, cause my work need your result as a baseline, so I wonder is
there anything wrong with my operation or code?

Best,
Le Zhang

Jonathan Herzig ***@***.***> 于2022年1月23日周日 15:12写道：
