### ISSUE TITLE
training is not working in my dir

### ISSUE THREAD

**Issue by m-ast** [jonathanherzig/span-based-sp#3]
Hello Herzig, 

When I ran the command `python3 span_based/run_span.py -d geo_iid -w -l` in my local directory, I got the error log (error.txt) and halt the program after just 10 minutes (timeout?).

[error.txt](https://github.com/jonathanherzig/span-based-sp/files/8608201/error.txt)

Please give me the details if you have seen anything similar to my error logs.

My environment 
> OS: Red Hat Enterprise Linux 8.2
> CUDA: 10.0.130.1
> torch: 1.2.0
> tqdm: 4.45.0
> other modules were loaded from requirements.txt in your directory

Thank you, 
Tomoya Kurosawa

**Comment by nixonjin** [comment]
自动回复：这里是金能征的邮箱，您的信件已被收入。This is Jin Nengzheng. Your letter have been received and will be disposed as soon as possible.

**Comment by m-ast** [comment]
Sorry, it works by changing CUDA's version. Closing this issue.
